In [3]:
# Creating An Array And Performing Addition Of Two Matrices Using list And NumPy Array 

import numpy as np
A = np.array([[0,6],[8,2]])
B = np.array([[4,1],[5,7]])
Result = A + B
print("Array A:\n",A)
print("\nArray B:\n",B)
print("\n Addition of A and B:\n",Result)

Array A:
 [[0 6]
 [8 2]]

Array B:
 [[4 1]
 [5 7]]

 Addition of A and B:
 [[ 4  7]
 [13  9]]
